\c mountain_db

DROP TABLE IF EXISTS songs;

CREATE TABLE songs (
 uri TEXT PRIMARY KEY NOT NULL UNIQUE,
 who_said UUID NOT NULL,
 A_Basin BOOLEAN NOT NULL DEFAULT FALSE,
 Copper_Mountain BOOLEAN NOT NULL DEFAULT FALSE,
 Eldora BOOLEAN NOT NULL DEFAULT FALSE,
 Vail_Resorts BOOLEAN NOT NULL DEFAULT FALSE,
 Winter_Park BOOLEAN NOT NULL DEFAULT FALSE,
 stamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);