\c mountain_db

CREATE TABLE songs (
 sid TEXT UNIQUE,
 inBasin BOOLEAN DEFAULT FALSE,
 inCopper BOOLEAN DEFAULT FALSE,
 inEldora BOOLEAN DEFAULT FALSE,
 inVail BOOLEAN DEFAULT FALSE,
 inPark BOOLEAN DEFAULT FALSE,
 inTHINGY BOOLEAN DEFAULT FALSE,
 stamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);